name: "🐛 Ошибка"
description: Расскажите о проблеме!
title: "🐛 [ОШИБКА] - <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Описание"
      description: Пожалуйста, введите подробное описание проблемы.
      placeholder: Краткое и подробное описание проблемы...
    validations:
      required: true